### ISSUE TITLE
NullPointerException on getAuthInteractiveCallback()

### ISSUE THREAD

**Issue by generosocarbone** [Azure-Samples/active-directory-android-native-v2#15]
`2018-12-12 20:00:39.883 8934-8963/? D/EGL_emulation: eglMakeCurrent: 0xa5d28d20: ver 2 0 (tinfo 0xa5d77a50)
2018-12-12 20:00:40.202 8934-8934/? I/LoginActivity: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
2018-12-12 20:00:40.202 8934-8934/? I/LoginActivity: unknown_error
2018-12-12 20:00:40.202 8934-8934/? I/LoginActivity: com.microsoft.identity.client.exception.MsalClientException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
2018-12-12 20:00:40.202 8934-8934/? W/System.err: com.microsoft.identity.client.exception.MsalClientException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
2018-12-12 20:00:40.202 8934-8934/? W/System.err:     at com.microsoft.identity.client.internal.controllers.ExceptionAdapter.msalExceptionFromException(ExceptionAdapter.java:108)
2018-12-12 20:00:40.202 8934-8934/? W/System.err:     at com.microsoft.identity.client.internal.controllers.MSALApiDispatcher$1.run(MSALApiDispatcher.java:81)
2018-12-12 20:00:40.202 8934-8934/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2018-12-12 20:00:40.202 8934-8934/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2018-12-12 20:00:40.202 8934-8934/? W/System.err:     at java.lang.Thread.run(Thread.java:761)
2018-12-12 20:00:40.202 8934-8934/? W/System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
2018-12-12 20:00:40.202 8934-8934/? W/System.err:     at com.microsoft.identity.common.internal.cache.MicrosoftStsAccountCredentialAdapter.getExpiresOn(MicrosoftStsAccountCredentialAdapter.java:231)
2018-12-12 20:00:40.202 8934-8934/? W/System.err:     at com.microsoft.identity.common.internal.cache.MicrosoftStsAccountCredentialAdapter.createAccessToken(MicrosoftStsAccountCredentialAdapter.java:78)
2018-12-12 20:00:40.202 8934-8934/? W/System.err:     at com.microsoft.identity.common.internal.cache.MicrosoftStsAccountCredentialAdapter.createAccessToken(MicrosoftStsAccountCredentialAdapter.java:45)
2018-12-12 20:00:40.202 8934-8934/? W/System.err:     at com.microsoft.identity.common.internal.cache.MsalOAuth2TokenCache.save(MsalOAuth2TokenCache.java:112)
2018-12-12 20:00:40.202 8934-8934/? W/System.err:     at com.microsoft.identity.client.internal.controllers.LocalMSALController.saveTokens(LocalMSALController.java:223)
2018-12-12 20:00:40.202 8934-8934/? W/System.err:     at com.microsoft.identity.client.internal.controllers.LocalMSALController.acquireToken(LocalMSALController.java:108)
2018-12-12 20:00:40.202 8934-8934/? W/System.err:     at com.microsoft.identity.client.internal.controllers.MSALInteractiveTokenCommand.execute(MSALInteractiveTokenCommand.java:60)
2018-12-12 20:00:40.202 8934-8934/? W/System.err:     at com.microsoft.identity.client.internal.controllers.MSALApiDispatcher$1.run(MSALApiDispatcher.java:70)
2018-12-12 20:00:40.202 8934-8934/? W/System.err: 	... 3 more`

**Comment by josephbnb** [comment]
Same issue for me in `msal:0.3.2-alpha`, any updates?

**Comment by vitalybibikov** [comment]
Have the same issue

**Comment by supreettare** [comment]
I am having same issue but I am using App Center Auth & not MSAL Nugets

**Comment by brspurri** [comment]
Same issue. I am using `AppCenter.Auth` *v2.6.2*, and the code:

```
UserInformation userInfo = await Auth.SignInAsync();
```
goes out to the browser, allows an Active Directory user to login and get redirected back to the app, at which point throws an exception:

```
[AppCenterAuth] User sign-in failed.
[AppCenterAuth] com.microsoft.identity.client.exception.MsalClientException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
[AppCenterAuth] 	at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(MsalExceptionAdapter.java:49)
[AppCenterAuth] 	at com.microsoft.identity.client.PublicClientApplication$4.onError(PublicClientApplication.java:1341)
[AppCenterAuth] 	at com.microsoft.identity.common.internal.controllers.ApiDispatcher$1$1.run(ApiDispatcher.java:97)
...
```

I would love to find a solution for this.
