### ISSUE TITLE
App crashes on opening with java.lang.String java.lang.Object.toString()' on a null object reference

### ISSUE THREAD

**Issue by Larrsenn** [Azure-Samples/active-directory-android-native-v2#17]
I've had this project work for me earlier and it still works for my colleges, but now when I try to open the app it crashes immediately on the getAccounts() part with this following stacktrace. Any idea on what's going on and whether I can fix it somehow on my machine? It happened after I updated kotlin to the newest version (1.3.11) in my android studio. I've tried uninstalling Android studio and installing it again, but the error still occurs.

2019-01-04 08:21:37.475 8405-8405/com.azuresamples.msalandroidapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.azuresamples.msalandroidapp, PID: 8405
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.azuresamples.msalandroidapp/com.azuresamples.msalandroidapp.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3037)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3172)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
        at com.microsoft.identity.common.internal.cache.AccountCredentialCache.getAccountsWithKeys(AccountCredentialCache.java:168)
        at com.microsoft.identity.common.internal.cache.AccountCredentialCache.getAccounts(AccountCredentialCache.java:184)
        at com.microsoft.identity.common.internal.cache.AccountCredentialCache.getAccountsFilteredBy(AccountCredentialCache.java:205)
        at com.microsoft.identity.common.internal.cache.MsalOAuth2TokenCache.getAccounts(MsalOAuth2TokenCache.java:337)
        at com.microsoft.identity.client.PublicClientApplication.getAccounts(PublicClientApplication.java:330)
        at com.azuresamples.msalandroidapp.MainActivity.onCreate(MainActivity.java:71)
        at android.app.Activity.performCreate(Activity.java:7149)
        at android.app.Activity.performCreate(Activity.java:7140)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3017)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3172) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6863) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by Larrsenn** [comment]
This issue no longer occurs after a few days of sickness - no idea what happened sadly.

**Comment by Larrsenn** [comment]
I was too fast, it was a try catch that caught it. It's still happening..

**Comment by Larrsenn** [comment]
It might have something to do with you being silently logged in it could seem.

**Comment by jbloomfield2** [comment]
this happens when I've logged in previously but  not when the app storage is cleared. I haven't been able to resolve this but have found a workaround for silently logging in.

probably not the best way to do this:
in the the aquiretoken onsucess callback, you need to get the homeaccountidentifier with
authResult.getAccount().getHomeAccountIdentifier().getIdentifier() and save it, perhaps in sharedprefs

then in onresume() you can do
IAccount acc = myapp.getaccount(homeaccountidentifier)
and pass the account object in to acquireTokenSilentAsync

**Comment by danieldobalian** [comment]
@Larrsenn thanks for the report, we'll take a look.

**Comment by iambmelt** [comment]
Issues appear related: https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/495

**Comment by samirkumar** [comment]
Got this issue with new app sample using msal0.3.1.-alpha. Uncaught Error: Intent filter for: BrowserTabActivity is missing.  Please refer to the MSAL readme. 
 com.microsoft.identity.client.PublicClientApplication.checkIntentFilterAddedToAppManifest(PublicClientApplication.java:1263)
[ERROR] :     com.microsoft.identity.client.PublicClientApplication.initializeApplication(PublicClientApplication.java:324)
[ERROR] :   com.microsoft.identity.client.PublicClientApplication.<init>(PublicClientApplication.java:219)

My JSON config has no path set for android:path. And browser tab activity is set as in manifest.xml,

	   <activity
            android:name="com.microsoft.identity.client.BrowserTabActivity">
            <intent-filter>

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                
                <data android:scheme="msal-xxxxxxx-clientID-xxxxx"
                    android:host= "https://localhost:xxxxx"
                    android:path= "/" />
            </intent-filter>
         </activity>

**Comment by iambmelt** [comment]
@samirkumar You'll see this issue when the `redirect_uri` provided in the app config doesn't match the registered `IntentFilter` in the `AndroidManifest.xml`

For MSAL, the suggested pattern to use for your redirect is:
`msauth://<package_name>.<signature_hash`

So for a sample app config such as:
```json
{
  "client_id" : "6d0db8c2-9f26-4417-8bde-3f0e3656f8e0",
  "authorization_user_agent" : "DEFAULT",
  "redirect_uri" : "msauth://com.sample.app/WxC6PxIyvbLkbFVtBI%2FitkW%2Fejk%3D",
  "multiple_clouds_supported":true,
  "broker_redirect_uri_registered": true,
  "authorities" : [
    {
      "type": "AAD",
      "audience": {
        "type": "AzureADandPersonalMicrosoftAccount"
      }
    }
  ]
}
```

Then the `IntentFilter` should look like:
```xml
        <activity
            android:name="com.microsoft.identity.client.BrowserTabActivity"
            android:launchMode="singleTask" >
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="msauth"
                    android:host="com.sample.app"
                    android:path="/WxC6PxIyvbLkbFVtBI/itkW/ejk="/>

            </intent-filter>
        </activity>
```

**Comment by RaviChavada-dev** [comment]
Microsoft login crashed, please help

Attempt to invoke interface method 'void com.microsoft.identity.client.ISingleAccountPublicClientApplication.signIn(android.app.Activity, java.lang.String, java.lang.String[], com.microsoft.identity.client.AuthenticationCallback)' on a null object reference

Thank you.

**Comment by iambmelt** [comment]
> Microsoft login crashed, please help
> 
> Attempt to invoke interface method 'void com.microsoft.identity.client.ISingleAccountPublicClientApplication.signIn(android.app.Activity, java.lang.String, java.lang.String[], com.microsoft.identity.client.AuthenticationCallback)' on a null object reference
> 
> Thank you.

@RaviChavada-dev Your PublicClientApplication object is `null` -- there is bug in your application: either you have not initialized this object, or you are attempting to use it before it has finished initializing
