### ISSUE TITLE
No Activity found to handle  AuthenticationActivity in msal library

### ISSUE THREAD

**Issue by NavalKishor** [Azure-Samples/active-directory-android-native-v2#5]
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.naval.libs/com.microsoft.identity.client.AuthenticationActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=https://www.xxxxlogin.com/... pkg=com.android.chrome launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } }
 at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3873)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3914)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3070)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6823)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

Caused by android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=https://www.xxxxlogin.com/... pkg=com.android.chrome launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } }
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1844)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1531)
       at android.app.Activity.startActivityForResult(Activity.java:4411)
       at android.app.Activity.startActivityForResult(Activity.java:4369)
       at android.app.Activity.startActivity(Activity.java:4708)
       at android.app.Activity.startActivity(Activity.java:4676)
       at com.microsoft.identity.client.AuthenticationActivity.onResume(SourceFile:237)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1277)
       at android.app.Activity.performResume(Activity.java:7140)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3850)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3914)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3070)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6823)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

In AndroidManifest.xml
 <activity
            android:name="com.microsoft.identity.client.BrowserTabActivity">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                
                            
                <data android:scheme="@string/msalid" android:host="auth" />
            </intent-filter>
        </activity>

Device Details
# Platform: android
# Date: 2017-11-23T06:34:00Z
# OS Version: 7.1.1
# Device: SM-N950U
# RAM Free: 14.6%
# Disk Free: 78.6%

**Comment by danieldobalian** [comment]
Closing since the sample has been refactored.
